name: CI/CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_ENV
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: './logs-to-slack/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./logs-to-slack/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |
          cd logs-to-slack
          npm install --production

      - name: Print version
        run: |
          echo Version: $RELEASE_VERSION

      - name: AWS Serverless Application Repository Action
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: logs-to-slack-sar-deployment
          S3_BUCKET_PREFIX: package
        run: |
          sam package --region $AWS_DEFAULT_REGION --s3-bucket $S3_BUCKET --s3-prefix $S3_BUCKET_PREFIX --template-file template.yaml --output-template-file packaged.yaml
          sam publish --region $AWS_DEFAULT_REGION --semantic-version ${{env.RELEASE_VERSION}} --template packaged.yaml
